version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRRES_PASSWORD: 123
      POSTGRES_DB: nest
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - katana
networks:
  katana: